Add compressbits and expandbits opcodes
eclipse-omr/omr pull request #7259
Opened 2024-02-08 16:43 UTC by Spencer-Comin

- Adds the following opcodes:
  - `lcompressbits`, `icompressbits`, `scompressbits`, `bcompressbits`
  - `lexpandbits`, `iexpandbits`, `sexpandbits`, `bexpandbits`
- Adds evaluators for Power and x86
- Adds simplifiers and value propagation
- Adds TRIL tests

See https://github.com/eclipse/omr/issues/7172

2024-02-08 16:44 UTC, Spencer-Comin commented
Relies on https://github.com/eclipse/omr/pull/7252 for TRIL tests to work correctly

2024-02-08 19:43 UTC, Spencer-Comin commented
@r30shah fyi

2024-04-10 22:12 UTC, Spencer-Comin commented
Instruction selection log excerpts:

# Power
### expandbits
```
------------------------------
 n3n      (  0)  ireturn                                                                              [      0xab8d6f3930] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=- nc=1
 n4n      (  0)    b2i (in GPR_0017)                                                                  [      0xab8d6f3970] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=11920 nc=1
 n5n      (  0)      bexpandbits (in GPR_0017)                                                        [      0xab8d6f39b0] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=11920 nc=2
 n6n      (  0)        bload  Parm  0<parm 0 B>[#389  Parm] [flags 0xc0000101 0x0 ]                   [      0xab8d6f39f0] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=- nc=0
 n7n      (  0)        bload  Parm  1<parm 1 B>[#390  Parm] [flags 0xc0000101 0x0 ] (in GPR_0016)     [      0xab8d6f3a30] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=11488 nc=0
------------------------------

 [      0xab8d772e00]   0       lbz     GPR_0016, [gr1, 8]              # SymRef  Parm  1<parm 1 B>[#390  Parm] [flags 0xc0000101 0x0 ]
 [      0xab8d773060]   0       lbz     GPR_0018, [gr1, 0]              # SymRef  Parm  0<parm 0 B>[#389  Parm] [flags 0xc0000101 0x0 ]
 [      0xab8d7730f0]   0       pdepd   GPR_0017, GPR_0018, GPR_0016
 [      0xab8d7731d0]   0       retn
 [      0xab8d773250]   0       blr
```
```
------------------------------
 n3n      (  0)  ireturn                                                                              [     0x8441b195000] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=- nc=1
 n4n      (  0)    s2i (in GPR_0016)                                                                  [     0x8441b195040] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=17328 nc=1
 n5n      (  0)      sexpandbits (in GPR_0018)                                                        [     0x8441b195080] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=17936 nc=2
 n6n      (  0)        sload  Parm  0<parm 0 C>[#389  Parm] [flags 0xc0000102 0x0 ]                   [     0x8441b1950c0] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=- nc=0
 n7n      (  0)        sload  Parm  1<parm 1 C>[#390  Parm] [flags 0xc0000102 0x0 ] (in GPR_0017)     [     0x8441b195100] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=17504 nc=0
------------------------------

 [     0x8441b214580]   0       lha     GPR_0017, [gr1, 8]              # SymRef  Parm  1<parm 1 C>[#390  Parm] [flags 0xc0000102 0x0 ]
 [     0x8441b2147e0]   0       lhz     GPR_0019, [gr1, 0]              # SymRef  Parm  0<parm 0 C>[#389  Parm] [flags 0xc0000102 0x0 ]
 [     0x8441b214870]   0       pdepd   GPR_0018, GPR_0019, GPR_0017
 [     0x8441b214900]   0       extsh   GPR_0016, GPR_0018
 [     0x8441b2149d0]   0       retn
 [     0x8441b214a50]   0       blr
```
```
------------------------------
 n3n      (  0)  ireturn                                                                              [     0x4e19246f050] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=- nc=1
 n4n      (  0)    iexpandbits (in GPR_0017)                                                          [     0x4e19246f090] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=38496 nc=2
 n5n      (  0)      iload  Parm  0<parm 0 I>[#389  Parm] [flags 0xc0000103 0x0 ]                     [     0x4e19246f0d0] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=- nc=0
 n6n      (  0)      iload  Parm  1<parm 1 I>[#390  Parm] [flags 0xc0000103 0x0 ] (in GPR_0016)       [     0x4e19246f110] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=38064 nc=0
------------------------------

 [     0x4e1925495d0]   0       lwz     GPR_0016, [gr1, 8]              # SymRef  Parm  1<parm 1 I>[#390  Parm] [flags 0xc0000103 0x0 ]
 [     0x4e192549830]   0       lwz     GPR_0018, [gr1, 0]              # SymRef  Parm  0<parm 0 I>[#389  Parm] [flags 0xc0000103 0x0 ]
 [     0x4e1925498c0]   0       pdepd   GPR_0017, GPR_0018, GPR_0016
 [     0x4e1925499a0]   0       retn
 [     0x4e192549a20]   0       blr
```
```
------------------------------
 n3n      (  0)  lreturn                                                                              [     0x605f1cb43d0] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=- nc=1
 n4n      (  0)    lexpandbits (in GPR_0017)                                                          [     0x605f1cb4410] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=22304 nc=2
 n5n      (  0)      lload  Parm  0<parm 0 J>[#389  Parm] [flags 0xc0000104 0x0 ] (in GPR_0018)       [     0x605f1cb4450] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=22480 nc=0
 n6n      (  0)      lload  Parm  1<parm 1 J>[#390  Parm] [flags 0xc0000104 0x0 ] (in GPR_0016)       [     0x605f1cb4490] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=21872 nc=0
------------------------------

 [     0x605f1d25690]   0       ld      GPR_0016, [gr1, 8]              # SymRef  Parm  1<parm 1 J>[#390  Parm] [flags 0xc0000104 0x0 ]
 [     0x605f1d258f0]   0       ld      GPR_0018, [gr1, 0]              # SymRef  Parm  0<parm 0 J>[#389  Parm] [flags 0xc0000104 0x0 ]
 [     0x605f1d25980]   0       pdepd   GPR_0017, GPR_0018, GPR_0016
 [     0x605f1d25a60]   0       retn
```

### compressbits
```
------------------------------
 n3n      (  0)  ireturn                                                                              [     0x72202073310] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=- nc=1
 n4n      (  0)    b2i (in GPR_0017)                                                                  [     0x72202073350] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=18384 nc=1
 n5n      (  0)      bcompressbits (in GPR_0017)                                                      [     0x72202073390] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=18384 nc=2
 n6n      (  0)        bload  Parm  0<parm 0 B>[#389  Parm] [flags 0xc0000101 0x0 ] (in GPR_0016)     [     0x722020733d0] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=17952 nc=0
 n7n      (  0)        bload  Parm  1<parm 1 B>[#390  Parm] [flags 0xc0000101 0x0 ]                   [     0x72202073410] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=- nc=0
------------------------------

 [     0x722020e4740]   0       lbz     GPR_0016, [gr1, 0]              # SymRef  Parm  0<parm 0 B>[#389  Parm] [flags 0xc0000101 0x0 ]
 [     0x722020e49a0]   0       lbz     GPR_0018, [gr1, 8]              # SymRef  Parm  1<parm 1 B>[#390  Parm] [flags 0xc0000101 0x0 ]
 [     0x722020e4a30]   0       pextd   GPR_0017, GPR_0016, GPR_0018
 [     0x722020e4b10]   0       retn
 [     0x722020e4b90]   0       blr
```
```
------------------------------
 n3n      (  0)  ireturn                                                                              [     0xb90c1793310] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=- nc=1
 n4n      (  0)    s2i (in GPR_0016)                                                                  [     0xb90c1793350] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=17952 nc=1
 n5n      (  0)      scompressbits (in GPR_0018)                                                      [     0xb90c1793390] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=18560 nc=2
 n6n      (  0)        sload  Parm  0<parm 0 C>[#389  Parm] [flags 0xc0000102 0x0 ] (in GPR_0017)     [     0xb90c17933d0] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=18128 nc=0
 n7n      (  0)        sload  Parm  1<parm 1 C>[#390  Parm] [flags 0xc0000102 0x0 ]                   [     0xb90c1793410] bci=[-1,0,-] rc=0 vc=35 vn=- li=2 udi=- nc=0
------------------------------

 [     0xb90c18047f0]   0       lha     GPR_0017, [gr1, 0]              # SymRef  Parm  0<parm 0 C>[#389  Parm] [flags 0xc0000102 0x0 ]
 [     0xb90c1804a50]   0       lhz     GPR_0019, [gr1, 8]              # SymRef  Parm  1<parm 1 C>[#390  Parm] [flags 0xc0000102 0x0 ]
 [     0xb90c1804ae0]   0       pextd   GPR_0018, GPR_0017, GPR_0019
 [     0xb90c1804b70]   0       extsh   GPR_0016, GPR_0018
 [     0xb90c1804c40]   0       retn
 [     0xb90c1804cc0]   0       blr
```
```
------------------------------
 n3n      (  0)  ireturn                                                                              [     0x2927bd51d60]  [...]

2024-06-07 18:41 UTC, r30shah requested changes

2024-06-07 18:41 UTC, r30shah commented on compiler/il/OMROpcodes.enum
> +   /* .description          = compress bits: equivalent to calling Integer.compress(a, b) */
It seems bit ambiguous what Integer.compress(a,b) is looking at the change just with OMR perspective.

2024-06-07 18:41 UTC, r30shah commented on compiler/optimizer/OMRSimplifierHandlers.cpp
> +template <typename T>
Can you add a high level description for this function in Comment? Also same for compressBits simplifier.

2024-06-07 18:41 UTC, r30shah commented on compiler/optimizer/OMRSimplifierHandlers.cpp
> +          performTransformation(s->comp(), "%sReduced %s of const src and const mask in node [%s] to const\n",
It may be more beneficial if someone tries to find out what transformed to print the node pointer (See other perform transformation usage).

2024-06-07 18:41 UTC, r30shah commented on compiler/optimizer/OMRSimplifierHandlers.cpp
> +      else if (mask == static_cast<T>(0) &&
Same comment as previous. Also please review and update further performTransformation messeges.

2024-11-28 14:53 UTC, Spencer-Comin commented
This depends on https://github.com/eclipse-omr/omr/pull/7564 to avoid a bug in the x86 codegen

2025-01-06 18:59 UTC, Spencer-Comin commented
@zl-wang For some reason I can't request a review from you through the GUI. Can I get your review on the P codegen changes here?

2025-01-07 17:05 UTC, zl-wang requested changes

2025-01-07 17:05 UTC, zl-wang commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
since `lbz/lhz/lwz`  meant zero-extension already (with resulting register upper bits cleared), i don't see why you cannot simplify the logic below to handle it consistently, i.e. you only need `rldicl` for cases where mask register pre-exists and types are not 64bit.

2025-01-07 17:05 UTC, zl-wang commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
Ditto.

2025-01-07 17:19 UTC, zl-wang commented
higher level comments:
1) since we are dealing with individual bits in these routines, semantically `b2i/s2i` (implying sign-extension), instead of bu2i/su2i (implying zero-extension, more likely resulting in a `nop`) are right?
2) what is the advantage of adding these one-off IL opcode vs. recognizing the specific methods?

2025-01-07 17:20 UTC, BradleyWood commented on compiler/x/i386/codegen/OMRTreeEvaluator.cpp
> +   return TR::TreeEvaluator::badILOpEvaluator(node, cg);
I am pretty sure these 32-bit opcodes are valid on 32-bit

2025-01-07 19:02 UTC, Spencer-Comin commented
@zl-wang

> 1. since we are dealing with individual bits in these routines, semantically b2i/s2i (implying sign-extension), instead of bu2i/su2i (implying zero-extension, more likely resulting in a nop) are right?

I'm not sure I understand the question.

> 2. what is the advantage of adding these one-off IL opcode vs. recognizing the specific methods?

There are a couple other potential uses for these operations (hashing [1], varint encode and decode idioms [2]), so adding them as IL opcodes lays the groundwork for accelerating those usecases in the future in a more platform-generic (and hopefully easier) way.

[1] https://github.com/eclipse-omr/omr/issues/7172#issuecomment-1819790979
[2] https://protobuf.dev/programming-guides/encoding/#varints

2025-01-07 19:22 UTC, zl-wang commented
is the sign-extended result the correct expectation? for example, bcompressbits can result in 0xFFFFFFFF? after all, these routines sound like bit-logical operations. on the other hand, hardware instruction result is naturally zero-extended in reality (i.e. if it is defined to be zero-extended, you definitely don't need those `exts*` instructions for better performance).

2025-01-07 19:38 UTC, Spencer-Comin commented
@zl-wang I'm assuming you are referring to the `extsh` in the `sexpandbits` and `scompressbits` examples in https://github.com/eclipse-omr/omr/pull/7259#issuecomment-2048523709. I generated those examples with some TRIL tests, but I was having trouble with the `sreturn` opcode so as a hack I used `s2i` and `ireturn` instead. The `s2i` is responsible for the `extsh` instruction, not the `sexpandbits` or `scompressbits`. Sorry for the confusion.

2025-01-07 19:53 UTC, zl-wang commented
i understand how `exts*` came by. my question was more about: semantically do we need those `*2i` conversions (of course, normally, disregarding your contrived IL cases)?

2025-01-07 20:04 UTC, Spencer-Comin commented
No, the conversion isn't semantically necessary

2025-01-07 20:27 UTC, zl-wang approved these changes

2025-01-14 22:56 UTC, hzongaro reviewed
Just a couple of questions about whether it’s conceivable that Tree Simplification or Value Propagation might be able to do anything with these operators.  The answer could be, “Wait and see, because we haven’t seen enough use yet.”

2025-01-14 22:56 UTC, hzongaro commented on compiler/optimizer/OMRSimplifierTable.enum
> +#define bexpandbitsSimplifierHandler dftSimplifier
Does it never happen that the operands are constants (e.g., second operand being all zeroes or all ones) that will allow simplification?

2025-01-14 22:56 UTC, hzongaro commented on compiler/optimizer/ValuePropagationTable.hpp
> +#define bexpandbitsVPHandler constrainChildren
Is it likely that we might have constraints on the operands that would allow constraints to be computed for the result of the operation?

2025-01-14 23:00 UTC, hzongaro commented on compiler/optimizer/ValuePropagationTable.hpp
> +#define bexpandbitsVPHandler constrainChildren
For instance, if we knew that the second operand of `icompressbits` had four bits set, the result would be in the range [0,15].

2025-01-16 19:43 UTC, Spencer-Comin commented
For tree simplification and value propagation, there are definitely things that could be done. The only immediate consumer of these opcodes is the Java `Integer`/`Long` `compress`/`expand` intrinsic methods https://github.com/eclipse-openj9/openj9/pull/19202. I haven't seen enough use of these methods "in the wild" to have any idea if they are actually used in situations where potential tree simplification and value propagation transformations could actually kick in. If/when we get to the additional uses in https://github.com/eclipse-omr/omr/pull/7259#issuecomment-2576022263, or if these methods see a lot more use, we can re-evaluate if we'll see a benefit from implementing the transformations.

**TL;DR:** Wait and see, because we haven’t seen enough use yet.

2025-02-03 17:29 UTC, Spencer-Comin commented on compiler/x/codegen/OMRTreeEvaluator.cpp
> +   bool nodeIs64Bit = TR::TreeEvaluator::getNodeIs64Bit(node, cg);
Looks like I forgot to update this evaluator when I separated out `lexpandbitsEvaluator`. Fixed in https://github.com/eclipse-omr/omr/commit/3dd70a3616ab031fe3bac492e506949e29d5ea4d.

2025-02-03 17:30 UTC, Spencer-Comin commented on compiler/x/codegen/OMRTreeEvaluator.cpp
> +   bool nodeIs64Bit = TR::TreeEvaluator::getNodeIs64Bit(node, cg);
Fixed in https://github.com/eclipse-omr/omr/commit/3dd70a3616ab031fe3bac492e506949e29d5ea4d.

2025-02-03 17:31 UTC, Spencer-Comin commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +         generateTrg1Src1Imm2Instruction(cg, TR::InstOpCode::rldicl, node, maskReg, maskReg, 0, maskConst);
Added logic in https://github.com/eclipse-omr/omr/commit/3dd70a3616ab031fe3bac492e506949e29d5ea4d to handle the zero-extension at compile time for constants.

2025-02-03 20:39 UTC, hzongaro commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +         generateTrg1Src1Imm2Instruction(cg, TR::InstOpCode::rldicl, node, maskReg, maskReg, 0, maskConst);
Looks good to me.  I'd like @zl-wang to double-check this change.

2025-02-03 20:41 UTC, hzongaro approved these changes
Your latest changes look good to me.  Assuming @zl-wang is good with the changes for Power, I am approving.

2025-02-03 20:53 UTC, zl-wang approved these changes
LGTM

2025-02-05 13:00 UTC, 0xdaryl commented on compiler/x/codegen/OMRTreeEvaluator.cpp
> +   TR_ASSERT(dt == TR::Int32 || dt == TR::Int16 || dt == TR::Int8, "compressbitsEvaluator only supports 32, 16, or 8 bits");
Make this a fatal assert.

2025-02-05 13:16 UTC, 0xdaryl commented on compiler/optimizer/OMRSimplifierTable.enum
> +#define bexpandbitsSimplifierHandler dftSimplifier
I have the same question, but I'm not clear what the answer was for this comment to be resolved.

Presumably, value propagation may leave us in a situation where both source and masks are constants which could be folded away.

2025-02-05 13:20 UTC, 0xdaryl commented on compiler/x/amd64/codegen/OMRTreeEvaluator.cpp
> +
Just a suggestion, not a requirement.  lcompress/lexpand evaluators are quite similar.  Consider commoning them if you can realize a space savings and it doesn't overly complicate the code.

2025-02-05 13:29 UTC, Spencer-Comin commented on compiler/optimizer/OMRSimplifierTable.enum
> +#define bexpandbitsSimplifierHandler dftSimplifier
@0xdaryl see https://github.com/eclipse-omr/omr/pull/7259#issuecomment-2596735153

I've decided to leave implementing Tree Simplification and Value Propagation for a future change if it becomes clear that they are actually used in situations where these opts would be worthwhile.

2025-02-05 22:22 UTC, Spencer-Comin commented
@hzongaro I'm re-requesting your review as well since I've reworked the x86 evaluators based on @0xdaryl's comments

2025-02-10 22:48 UTC, hzongaro reviewed
Sorry - I had a late question in my re-review.

Also it might be a good idea to add tril tests for `compressbits` and `expandbits` for the various sizes of operands.

2025-02-10 22:48 UTC, hzongaro commented on compiler/x/codegen/OMRTreeEvaluator.cpp
> +      // src needs to be zero-extended to 32 bits
I've been puzzling about this.  Is there a case where zero-extending the source would yield a different result from zero-extending the mask for `{b|s}compressbits`?  If so, I think it would be worthwhile adding a comment giving examples.

If not, I think you would be able to change this to zero-extend the mask and share code between `compressbitsEvaluator` and `expandbitsEvaluator` in the same way that you did with `lcompressbitsEvaluator` and `lexpandbitsEvaluator`.

2025-02-11 00:25 UTC, hzongaro commented
> Also it might be a good idea to add tril tests for `compressbits` and `expandbits` for the various sizes of operands.

Actually, please add tril tests in a follow up pull request; there's no need to hold up this pull request with that change.  I was particularly worried about the `TR::Int8` and `TR::Int16` variations which probably aren't being exercised by downstream projects.

2025-02-11 21:03 UTC, Spencer-Comin commented on compiler/x/codegen/OMRTreeEvaluator.cpp
> +      // src needs to be zero-extended to 32 bits
I revisited the need for zero extension and I have a couple observations to modify my implementations here:
- zero extension is unnecessary for `expandbits`
- either zero extending the source or mask will give the same result for `compressbits`

After adding these modifications `compressbitsEvaluator` and `expandbitsEvaluator` will be more different and might be better left separate.

2025-02-20 18:21 UTC, zl-wang commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +      }
are these methods only existing in java versions later than java8? otherwise, you need to consider for 32bit JVMs.

2025-02-20 18:21 UTC, zl-wang commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
you seemed not concerned with zero-extension as in compressingBits methods. unless bits deposited beyond type-size are taken as irrelevant, you should deal with it as well.

2025-02-20 18:35 UTC, hzongaro commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +      }
This is an important point.  The methods only exist in Java 19 and later.  However, as these are fully-fledged operators in the IL, It's conceivable that they will be used in other contexts, so 32-bit support would still be needed.

2025-02-20 18:45 UTC, Spencer-Comin commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
I'm assuming bits deposited beyond the type-size are taken as irrelevant

2025-02-21 00:53 UTC, 0xdaryl commented on compiler/x/codegen/OMRTreeEvaluator.cpp
> +      TR::MemoryReference *srcMR = generateX86MemoryReference(maskNode, cg);
Should this be `srcNode` rather than `maskNode` ?

Apologies, but I think I asked this before and if you answered it I don't recall your response.

2025-02-21 14:31 UTC, Spencer-Comin commented on compiler/x/codegen/OMRTreeEvaluator.cpp
> +      TR::MemoryReference *srcMR = generateX86MemoryReference(maskNode, cg);
Yes that should be `srcNode`. I did a whole refactor and made the same mistake again 🤦‍♂️. I'll get that fixed.

2025-02-21 21:54 UTC, hzongaro reviewed
I think the changes for x86 look good.  I just have one small comment.  I also need to  double-check the uses of `decNodeReferenceCounts` versus `decReferenceCount`.

2025-02-27 22:18 UTC, hzongaro approved these changes

2025-02-28 11:11 UTC, 0xdaryl approved these changes

2025-02-28 16:26 UTC, hzongaro commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
@zl-wang, I just wanted to double-check this point with you.  Does the p code generation require the results of `TR::Int8` and `TR::Int16` operations to be sign extended to the size of the register, or will later operations perform the sign extension as required?  Will the bits that are deposited beyond the size of the result type yield unexpected results from later operations?

2025-02-28 16:51 UTC, zl-wang commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
these are bit operations so that it was unclear to me whether the result should be expected to be signed, unsigned, or irrelevant. For typical data handling though, the convention (on p) was: guarantee the sign or zero extension up to the default integer type in register (i.e. 32bit). At present, `iload` on p is still using `lwz`, instead of `lwa`.  for byte/short, on the other hand, they need to be zero or sign extended appropriately (at least for the 32bit guarantee).

2025-02-28 21:31 UTC, hzongaro commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
OK, so I think that means @Spencer-Comin will need to sign-extend the results for `TR::Int8` and `TR::Int16` for Power.

2025-03-03 13:48 UTC, Spencer-Comin commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
> guarantee the sign or zero extension up to the default integer type in register

@zl-wang does this mean (1) extend `TR::Int8` and `TR::Int16` results to 32 bits for both 32 and 64 bit modes, or (2) extend `TR::Int8` and `TR::Int16` results to 32 bits for 32 bit mode and extend `TR::Int8`, `TR::Int16`, and `TR::Int32` bit results to 64 bits for 64 bit mode?

2025-03-03 13:52 UTC, zl-wang commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
simply extend to the register width will fulfill the commitment ... extsb and extsh respectively

2025-03-03 13:55 UTC, zl-wang commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
isn't that a requirement across platforms more or less as well? i don't see this as POWER specific

2025-03-03 14:03 UTC, Spencer-Comin commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
I don't believe other platforms make any guarantee on how the bits of the result register beyond the result size are affected by an evaluator (i.e., it's ok to leave garbage in those bits), @hzongaro @r30shah @knn-k is that correct?

2025-03-03 14:06 UTC, Spencer-Comin commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
> simply extend to the register width will fulfill the commitment ... extsb and extsh respectively

fixed in latest push https://github.com/eclipse-omr/omr/commit/0b8e73ee9129b3f0c4ab6a75ed4e328b8ea96f63

2025-03-03 16:42 UTC, zl-wang commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
what happens in reality on other platforms if you use these results as e.g. array index?

2025-03-03 20:57 UTC, hzongaro commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
I spent some time last week looking at how x86 code generation handles one byte and two values.  It was my impression that the contents of the upper portions of registers won't have an impact, but I didn't do a complete survey, so I very well could be mistaken.

@0xdaryl, do you know the answer?  Should @Spencer-Comin sign extend the results to 32 bits on x86?

2025-03-03 23:20 UTC, knn-k commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
AArch64 usually handles 8- and 16-bit data (signed/unsigned) by extending them to 32-bit wide when they are in registers.

2025-03-05 13:05 UTC, 0xdaryl commented on compiler/x/codegen/OMRTreeEvaluator.cpp
> +   }
Sorry for catching this late, but this evaluator should live in `amd64` (not common code) because it uses an instruction that is only available on 64-bit, and you've already introduced a special evaluator in `i386`.

2025-03-05 13:05 UTC, 0xdaryl commented on compiler/x/codegen/OMRTreeEvaluator.cpp
> +   }
Sorry for catching this late, but this evaluator should live in `amd64` (not common code) because it uses an instruction that is only available on 64-bit, and you've already introduced a special evaluator in `i386`.

2025-03-05 14:06 UTC, r30shah approved these changes
LGTM

2025-03-05 16:06 UTC, 0xdaryl approved these changes

2025-03-05 19:17 UTC, hzongaro commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +
From off-line discussion of this question, @0xdaryl indicated that the x86 code generation does not expect the results of `TR::Int8` and `TR::Int16` operations to have been sign-extended to the full width of a 32-bit register.  If any subsequent operation on those results &mdash; for example, `b2i` or `s2i` &mdash; needs to have a full 32-bit value to operate on a register, that subsequent operation is responsible for sign extending the 8 or 16-bit value.

2025-03-05 19:39 UTC, Spencer-Comin commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +   generateTrg1Src2Instruction(cg, TR::InstOpCode::pextd, node, resReg, srcReg, maskReg);
I'm not sure. @zl-wang do we want to guarantee sign extension or zero extension here? Currently solution here with zero extension on one of the operand guarantees that the result is zero extended.

2025-03-05 19:57 UTC, zl-wang commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +   generateTrg1Src2Instruction(cg, TR::InstOpCode::pextd, node, resReg, srcReg, maskReg);
agree with that, given the type

2025-03-05 19:58 UTC, Spencer-Comin commented on compiler/p/codegen/OMRTreeEvaluator.cpp
> +   generateTrg1Src2Instruction(cg, TR::InstOpCode::pextd, node, resReg, srcReg, maskReg);
Added sign extension for `bcompressbits` and `scompressbits` in https://github.com/eclipse-omr/omr/commit/b9b1f48dfb9ed33785e9ee5def199220f8c76ff8

2025-03-05 20:16 UTC, hzongaro commented
Jenkins build all

2025-03-05 21:52 UTC, Spencer-Comin commented
The failure on x86 is an instruction encoding failure
```
16:11:07  51: [0;32m[----------] [m16 tests from RegRegRegParallelBitOpsEncTest/XRegRegRegEncEncodingTest
16:11:07  51: /home/jenkins/workspace/Build/fvtest/compilerunittest/x/BinaryEncoder.cpp:567: Failure
16:11:07  51:       Expected: std::get<5>(GetParam())
16:11:07  51:       Which is: [ c4 e2 73 f5 c3 ]
16:11:07  51: To be equal to: encodeInstruction(instr)
16:11:07  51:       Which is: [ f2 0f 30 f5 c3 ]
16:11:07  51: [0;31m[  FAILED  ] [mRegRegRegParallelBitOpsEncTest/XRegRegRegEncEncodingTest.encode/0, where GetParam() = (707, 1, 3, 2, 2, [ c4 e2 73 f5 c3 ]) (0 ms)
```

Odd that `pdep` is getting encoded wrong here, but all my testing passed... I'm looking into this

2025-03-05 22:00 UTC, BradleyWood commented
You have to force VEX encoding in your test. Otherwise it tries to use legacy encoding for which that instruction does not exist in legacy mode.

2025-03-06 22:02 UTC, merged